[package]
name = "kameo-test"
version = "0.1.0"
edition = "2021"

[dependencies]
kameo = "0.9.0"
tokio = { version = "1.38.0", features = ["full"] }
anyhow = "1.0.86"
log = "0.4"
serde = { version = "1.0.203", features = ["derive"] }
env_logger = "0.10"